### ISSUE TITLE
No Directory Listing with -d

### ISSUE THREAD

**Issue by cawoodm** [avih/miniweb#1]
Running miniweb with `-d` I would expect a directory listing. Nope.
![cap](https://user-images.githubusercontent.com/498834/30518373-7e096ba2-9b7c-11e7-9629-99045fb532a4.JPG)

**Comment by cawoodm** [comment]
![cap](https://user-images.githubusercontent.com/498834/30518384-d8160632-9b7c-11e7-9832-0d3f86a53076.JPG)

**Comment by avih** [comment]
`-d` is to _disallow_ directory listing. I.e. by default directory listing is enabled. I also tried it and it does seem to behave as expected.

I also just pushed a commit to make it clearer on the help page, which now looks like so:
```
$ ./miniweb -h
MiniWeb-avih https://github.com/avih/miniweb (built on Sep 17 2017)
Originally: (C)2005-2013 Written by Stanley Huang <stanleyhuangyc@gmail.com>

Usage: miniweb  -h      : display this help screen
                -v      : log status/error info
                -p      : specifiy http port [default 80]
                -i      : interface [default 0.0.0.0]
                -r      : specify http document directory [default htdocs]
                -l      : specify log file
                -m      : specifiy max clients [default 32]
                -M      : specifiy max clients per IP
                -s      : specifiy download speed limit in KB/s [default: none]
                -n      : disallow multi-part download [default: allow]
                -d      : disallow directory listing [default: allow]
```

Can you confirm it works as expected for you? I.e. by default listing is enabled, and if you use `-d` then listing is disabled?

**Comment by avih** [comment]
I'm closing the issue assuming your issue was incorrect arguments usage.

Feel free to post here again if removing `-d` doesn't fix it for you.
