### ISSUE TITLE
Not list big file

### ISSUE THREAD

**Issue by Neboer** [avih/miniweb#11]
Miniweb doesn't list my local big file. The size of my file is 13.3GB but not shown on miniweb page.

**Comment by avih** [comment]
Which OS/version? is it 32 or 64 bits?

**Comment by Neboer** [comment]
Windows10 64bit, compiled with the newest VS2019

**Comment by avih** [comment]
What happens if you try the executable at the release pages (the zip contains a windows executable)? It's compiled as 32  bits but I just tested it on windows 8 64 and it listed correctly a 6.3G file.

The file miniweb-2017-09-17.zip here https://github.com/avih/miniweb/releases

**Comment by avih** [comment]
Please re-open or add a comment if you still have an issue.
