### ISSUE TITLE
Build with MSYS2 error in windows

### ISSUE THREAD

**Issue by QQ2017** [avih/miniweb#14]
C:\Users\admin\Desktop\miniweb-master>make
cc -DWIN32 -c -o httppil.o -O3 -Wunused-result httppil.c
In file included from /usr/include/w32api/winsock2.h:56,
                 from httppil.h:24,
                 from httppil.c:19:
/usr/include/w32api/psdk_inc/_fd_types.h:100:2: warning: #warning "fd_set and as
sociated macros have been defined in sys/types.      This can cause runtime prob
lems with W32 sockets" [-Wcpp]
  100 | #warning "fd_set and associated macros have been defined in sys/types.
\
      |  ^~~~~~~
In file included from httppil.h:24,
                 from httppil.c:19:
/usr/include/w32api/winsock2.h:1025:34: error: conflicting types for 'select'
 1025 |   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set
*writefds,fd_set *exceptfds,const PTIMEVAL timeout);
      |                                  ^~~~~~
In file included from /usr/include/sys/types.h:50,
                 from /usr/include/stdio.h:61,
                 from httppil.c:9:
/usr/include/sys/select.h:62:5: note: previous declaration of 'select' was here
   62 | int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
      |     ^~~~~~
In file included from httppil.c:19:
httppil.h:59:16: error: conflicting types for 'pthread_t'
   59 | typedef HANDLE pthread_t;
      |                ^~~~~~~~~
In file included from /usr/include/sys/types.h:223,
                 from /usr/include/stdio.h:61,
                 from httppil.c:9:
/usr/include/sys/_pthreadtypes.h:16:45: note: previous declaration of 'pthread_t
' was here
   16 | typedef struct __pthread_t {char __dummy;} *pthread_t;
      |                                             ^~~~~~~~~
In file included from httppil.c:19:
httppil.h:60:16: error: conflicting types for 'pthread_mutex_t'
   60 | typedef HANDLE pthread_mutex_t;
      |                ^~~~~~~~~~~~~~~
In file included from /usr/include/sys/types.h:223,
                 from /usr/include/stdio.h:61,
                 from httppil.c:9:
/usr/include/sys/_pthreadtypes.h:17:51: note: previous declaration of 'pthread_m
utex_t' was here
   17 | typedef struct __pthread_mutex_t {char __dummy;} *pthread_mutex_t;
      |                                                   ^~~~~~~~~~~~~~~
In file included from httppil.c:28:
win32/win_compat.h: In function 'cc_get_out_console_handle':
win32/win_compat.h:184:14: warning: implicit declaration of function '_fileno';
did you mean 'fileno'? [-Wimplicit-function-declaration]
  184 |     int fd = _fileno(f);
      |              ^~~~~~~
      |              fileno
win32/win_compat.h:186:9: warning: implicit declaration of function '_isatty' [-
Wimplicit-function-declaration]
  186 |     if (_isatty(fd) &&
      |         ^~~~~~~
win32/win_compat.h: In function 'write_console_text':
win32/win_compat.h:199:22: warning: implicit declaration of function 'wcslen' [-
Wimplicit-function-declaration]
  199 |     size_t out_len = wcslen(out);
      |                      ^~~~~~
win32/win_compat.h: In function 'cc_fopen':
win32/win_compat.h:294:16: warning: implicit declaration of function '_wfopen';
did you mean '_lopen'? [-Wimplicit-function-declaration]
  294 |     FILE *rv = _wfopen(wfname, wmode);
      |                ^~~~~~~
      |                _lopen
win32/win_compat.h:294:16: warning: initialization of 'FILE *' {aka 'struct __sF
ILE64 *'} from 'int' makes pointer from integer without a cast [-Wint-conversion
]
win32/win_compat.h: In function 'cc_open':
win32/win_compat.h:306:14: warning: implicit declaration of function '_wopen'; d
id you mean '_lopen'? [-Wimplicit-function-declaration]
  306 |     int rv = _wopen(wfname, oflags);
      |              ^~~~~~
      |              _lopen
win32/win_compat.h: At top level:
win32/win_compat.h:366:19: warning: 'struct _stat64' declared inside parameter l
ist will not be visible outside of this definition or declaration
  366 | #define cc_stat_s _stat64
      |                   ^~~~~~~
win32/win_compat.h:366:19: note: in definition of macro 'cc_stat_s'
  366 | #define cc_stat_s _stat64
      |                   ^~~~~~~
win32/win_compat.h: In function 'cc_stat':
win32/win_compat.h:369:14: warning: implicit declaration of function '_wstat64'
[-Wimplicit-function-declaration]
  369 |     int rv = _wstat64(wp, ss);
      |              ^~~~~~~~
httppil.c: In function 'IsDir':
httppil.c:140:19: error: storage size of 'stDirInfo' isn't known
  140 |  struct cc_stat_s stDirInfo;
      |                   ^~~~~~~~~
In file included from httppil.c:19:
httppil.c: In function 'ReadDir':
httppil.h:29:18: warning: implicit declaration of function '_snprintf'; did you
mean 'asnprintf'? [-Wimplicit-function-declaration]
   29 | #define snprintf _snprintf
      |                  ^~~~~~~~~
httppil.h:29:18: note: in definition of macro 'snprintf'
   29 | #define snprintf _snprintf
      |                  ^~~~~~~~~
httppil.c: In function 'IsFileExist':
httppil.c:220:19: error: storage size of 'stat_ret' isn't known
  220 |  struct cc_stat_s stat_ret;
      |                   ^~~~~~~~
make: *** [Makefile:44: httppil.o] Error 1

**Comment by avih** [comment]
This is because it's incorrectly detected as a windows build in MSYS2 mode (not mingw32 or 64) and in cygwin.

Either build it as pure mingw by starting one of the mingw MSYS2 shortcuts and then run `make`, or edit [`Makefile` at line 11](https://github.com/avih/miniweb/blob/master/Makefile#L11) and change `WINDIR` to something which won't get detected (e.g. change it to `WINDIRXXX`), and then it can be built in pure MSYS2 or cygwin.

I won't fix it though because the project is no longer maintained.

**Comment by QQ2017** [comment]
> This is because it's incorrectly detected as a windows build in MSYS2 mode (not mingw32 or 64) and in cygwin.
> 
> Either build it as pure mingw by starting one of the mingw MSYS2 shortcuts and then run `make`, or edit [`Makefile` at line 11](https://github.com/avih/miniweb/blob/master/Makefile#L11) and change `WINDIR` to something which won't get detected (e.g. change it to `WINDIRXXX`), and then it can be built in pure MSYS2 or cygwin.
> 
> I won't fix it though because the project is no longer maintained.

Thank you ，I build it successful.

**Comment by avih** [comment]
You're welcome.
