### ISSUE TITLE
method post

### ISSUE THREAD

**Issue by ghost** [avih/miniweb#3]
Hi,

I need to use the method post ( not for file ) but for fields. 

Is it possible?

How can I get the value from post?

**Comment by avih** [comment]
> Is it possible?

Not possible. I completely disabled the POST method at this commit: f48bb0b658fb13666ab9f0a61555d873fdf096aa because it was, IMO, mostly broken and also a security issue. See more details at the commit message at the link.

At this time I don't have plans to re-enable it.

You could, however, revert this commit, build it, and check if it fits your needs.

**Comment by avih** [comment]
> but for fields

What do you mean by this? what code will check the fields and make some decision depending on their values?

**Comment by ghost** [comment]
I would like to get values from a simple method post like this:
```
<form method=post>
 <input type=name value=test />
 <input type=submit name=action value=send />
</form>
```

I can not to use GET because it is limited.

**Comment by avih** [comment]
I know how you send with post, but I asked what code would _receive_ the post data? It's not a dynamic server, there is no CGI or active pages, so which program would receive the data and act upon it?

**Comment by ghost** [comment]
Understand.

Can you tell me only where is stored the post DATA when received?

I have plan in change it and add my C codes to read the post data and send a return as dynamic data.

Thanks for attention.

**Comment by avih** [comment]
> Can you tell me only where is stored the post DATA when received?

I don't know. I didn't write this server - I just improved it a little.

As far as I can tell, it was used to upload files. But I showed you which commit disabled it, so just revert this commit (with `git revert f48bb0b`), compile it yourself, and check if it fits your needs.

**Comment by ghost** [comment]
Oh. ok.

Thanks
